version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - selltech

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: selltech
      POSTGRES_USER: selltech
      POSTGRES_PASSWORD: selltech
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - selltech
networks:
  selltech:
      driver: bridge